"""Pin the Crontab Entries artifact (scripts/artifacts/linuxCron.py, linuxCrontabEntries).

USER_KNOWN is var/spool/cron/crontabs/parallels of ubuntu2604_arm64_crontab byte for byte: the file crontab 3.0pl1-200ubuntu1
wrote when it installed a known file. For every line below that cron accepts, the expected setting or command is
what cron's own load_env() and load_entry(), built from that package's sources, read from it; cron rejects the
system line '* * * * *  root', whose user name runs to the end of the line.
"""
import os
import pathlib
import sys
import tempfile
import types
import unittest
from collections import Counter
from datetime import datetime, timezone
from unittest import mock

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

# pylint: disable=wrong-import-position
from scripts.artifacts import linuxCron as lc
# pylint: enable=wrong-import-position

USER_KNOWN = (b'# DO NOT EDIT THIS FILE - edit the master and reinstall.\n'
              b'# (/home/parallels/crontab_known.txt installed on Tue Sep 29 10:08:38 2026)\n'
              b'# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)\n'
              b'# DLEAPP known crontab alpha\nMAILTO=""\nSHELL=/bin/bash\n# a job on 1 January at 03:07\n'
              b'7 3 1 1 * /usr/bin/true dleapp-known-yearly\n# runs at boot\n@reboot /usr/bin/true dleapp-known-reboot\n'
              b'# a disabled job\n#15 4 * * 0 /usr/bin/true dleapp-known-disabled\n'
              b'*/59 2 29 2 * /usr/bin/true dleapp-known-leapday > /dev/null 2>&1\n')


def rows(data, system=False):
    counts = Counter()
    return lc.crontab_rows(data, system, counts), counts


class LoadEnvTest(unittest.TestCase):
    def test_settings_cron_reads(self):
        for line, want in ((b'MAILTO=""', (b'MAILTO', b'')), (b'EMPTY=', (b'EMPTY', b'')),
                           (b'PATH = /usr/bin:/bin', (b'PATH', b'/usr/bin:/bin')),
                           (b'"QUOTED NAME" = "a value "', (b'QUOTED NAME', b'a value')),
                           (b"X='single'", (b'X', b'single')), (b'SPACED   =   spaced value  ', (b'SPACED', b'spaced value')),
                           (b'TAB\t=\tv\tw', (b'TAB', b'v\tw')), (b'A="\'x\'"', (b'A', b'x')), (b'=foo', (b'', b'foo')),
                           (b'A=b\r', (b'A', b'b')), (b'A=x#y', (b'A', b'x#y')), (b'@daily =x', (b'@daily', b'x')),
                           (b"'X'=y", (b'X', b'y')), (b'"N" = v w', (b'N', b'v w'))):
            with self.subTest(line=line):
                self.assertEqual(lc.load_env(line), want)

    def test_lines_that_are_not_settings(self):
        for line in (b'* * * * * true', b'A', b'A B=c', b'"A=B"=c', b'A="b', b'A="b" c', b"'A'", b'7 3 * * * X=y'):
            with self.subTest(line=line):
                self.assertIsNone(lc.load_env(line))

    def test_a_line_ending_at_an_opening_quote(self):
        for line in (b'"', b'A="', b"A= '"):
            with self.subTest(line=line):
                self.assertIs(lc.load_env(line), lc.UNDEFINED)

    def test_cron_keeps_the_first_998_characters(self):
        self.assertEqual(lc.load_env(b'A=' + b'x' * 1500), (b'A', b'x' * 996))
        self.assertEqual(lc.load_env(b'A=' + b'x' * 996), (b'A', b'x' * 996))


class SplitJobTest(unittest.TestCase):
    def test_five_fields_and_the_command(self):
        self.assertEqual(lc.split_job(b'7 3\t1  1 *   /bin/true  a ', False),
                         (b'7', b'3', b'1', b'1', b'*', b'', b'', b'/bin/true  a '))

    def test_a_keyword(self):
        self.assertEqual(lc.split_job(b'@reboot\t /bin/true', False), (b'', b'', b'', b'', b'', b'@reboot', b'', b'/bin/true'))
        self.assertEqual(lc.split_job(b'@reboot', False)[5:], (b'@reboot', b'', b''))

    def test_a_system_line_keeps_blanks_after_the_one_that_ends_the_user(self):
        self.assertEqual(lc.split_job(b'17 * * * * root    cd /', True)[6:], (b'root', b'   cd /'))
        self.assertEqual(lc.split_job(b'@daily root\tx', True)[5:], (b'@daily', b'root', b'x'))
        self.assertEqual(lc.split_job(b'* * * * *  root', True)[6:], (b'root', b''))

    def test_fewer_than_five_fields(self):
        self.assertIsNone(lc.split_job(b'* * * *', False))
        self.assertIsNone(lc.split_job(b'* * * * ', False))
        self.assertEqual(lc.split_job(b'* * * * *', False)[7], b'')


class RowsTest(unittest.TestCase):
    def test_the_known_user_crontab(self):
        found, counts = rows(USER_KNOWN)
        self.assertEqual(counts, Counter())
        self.assertEqual([r[1] for r in found], ['Comment'] * 4 + ['Environment'] * 2 + ['Comment', 'Job'] * 2
                         + ['Comment', 'Comment', 'Job'])
        self.assertEqual(len(found), 13)
        work = [r for r in found if r[1] != 'Comment']
        self.assertEqual([r[0] for r in work], [5, 6, 8, 10, 13])
        self.assertEqual(work[0][10:12], ('MAILTO', ''))
        self.assertEqual(work[2][2:10], ('7', '3', '1', '1', '*', '', '', '/usr/bin/true dleapp-known-yearly'))
        self.assertEqual(work[3][7], '@reboot')
        self.assertEqual(work[4][12], '*/59 2 29 2 * /usr/bin/true dleapp-known-leapday > /dev/null 2>&1')
        self.assertEqual(found[11], (12, 'Comment', *('',) * 10, '#15 4 * * 0 /usr/bin/true dleapp-known-disabled'))

    def test_comments_blank_lines_and_other_lines(self):
        found, counts = rows(b'  # c\n\t\n* * *\n"\nA=1\x00B=2\n\xff=\xfe\n')
        self.assertEqual([(r[0], r[1]) for r in found], [(1, 'Comment'), (3, 'Other'), (4, 'Other'), (5, 'Other'),
                                                          (6, 'Environment')])
        self.assertEqual(found[0][12], '  # c')
        self.assertEqual(found[4][10:], ('\\xff', '\\xfe', '\\xff=\\xfe'))
        self.assertEqual(counts, Counter({lc.UNDEFINED: 1, lc.NUL: 1}))

    def test_a_last_line_with_no_newline(self):
        self.assertEqual(rows(b'A=1')[1], Counter({lc.NO_NEWLINE: 1}))
        self.assertEqual(rows(b'A=1\n\r')[1], Counter({lc.NO_NEWLINE: 1}))
        self.assertEqual(rows(b'A=1\n# c')[1], Counter())
        self.assertEqual(rows(b'A=1\n \t')[1], Counter())

    def test_a_setting_or_job_at_line_10004(self):
        self.assertEqual(rows(b'A=1\n' * 10003)[1], Counter())
        self.assertEqual(rows(b'A=1\n' * 10004)[1], Counter({lc.TOO_LONG: 1}))
        self.assertEqual(rows(b'A=1\n' * 10003 + b'# c\n' * 5)[1], Counter())
        self.assertEqual(rows(b'# c\n' * 10003 + b'A=1\n')[1], Counter({lc.TOO_LONG: 1}))

    def test_a_command_of_999_characters(self):
        self.assertEqual(rows(b'* * * * * ' + b'c' * 998 + b'\n')[1], Counter())
        self.assertEqual(rows(b'* * * * * ' + b'c' * 999 + b'\n')[1], Counter({lc.LONG_COMMAND: 1}))


class HeaderAndKindTest(unittest.TestCase):
    def test_the_header_crontab_writes(self):
        self.assertEqual(lc.installed_header(USER_KNOWN.split(b'\n', 3)[:3]),
                         ('Tue Sep 29 10:08:38 2026', '/home/parallels/crontab_known.txt'))
        self.assertEqual(lc.installed_header(USER_KNOWN.split(b'\n', 4)[1:4]), ('', ''))
        first, second, third = USER_KNOWN.split(b'\n', 3)[:3]
        self.assertEqual(lc.installed_header([b'# DO NOT EDIT', second, third]), ('', ''))
        self.assertEqual(lc.installed_header([first, second, b'# (another comment)']), ('', ''))

    def test_crontab_kind(self):
        self.assertEqual(lc.crontab_kind('var/spool/cron/crontabs/alice'), 'User')
        self.assertEqual(lc.crontab_kind('lba0/etc/crontab'), 'System')
        self.assertEqual(lc.crontab_kind('etc/cron.d/anacron'), 'cron.d')
        self.assertIsNone(lc.crontab_kind('etc/cron.d/sub/x'))
        self.assertIsNone(lc.crontab_kind('var/spool/cron/crontabs/sub/x'))
        self.assertIsNone(lc.crontab_kind('opt/etc/crontab/x'))
        self.assertIsNone(lc.crontab_kind('home/alice/crontab'))


class FakeContext:
    def __init__(self, paths, root, seeker=None):
        self.paths, self.root, self.seeker = paths, root, seeker

    def get_files_found(self):
        return self.paths

    def get_relative_path(self, path):
        return os.path.relpath(path, self.root).replace(os.sep, '/')

    def get_seeker(self):
        if self.seeker is None:
            raise ValueError('no seeker')
        return self.seeker


class ArtifactTest(unittest.TestCase):
    def write(self, root, rel, data):
        path = os.path.join(root, *rel.split('/'))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'wb') as handle:
            handle.write(data)
        return path

    def test_artifact(self):
        with tempfile.TemporaryDirectory() as root:
            user = self.write(root, 'var/spool/cron/crontabs/parallels', USER_KNOWN)
            system = self.write(root, 'etc/crontab', b''.join(USER_KNOWN.splitlines(True)[:3]) + b'SHELL=/bin/sh\n17 * * * * root cd /\n')
            dotted_user = self.write(root, 'var/spool/cron/crontabs/first.last', b'A=1\n')
            crond = self.write(root, 'etc/cron.d/x', b'# only a comment\n')
            dotted = self.write(root, 'etc/cron.d/a.b', b'A=1\n')
            hidden = self.write(root, 'var/spool/cron/crontabs/.x', b'A=1\n')
            empty = self.write(root, 'etc/cron.d/.placeholder', b'\n')
            nested = self.write(root, 'etc/cron.d/sub/y', b'A=1\n')
            infos = {user: types.SimpleNamespace(modification_date=1790690918, source_path='x')}
            seeker = types.SimpleNamespace(file_infos=infos)
            paths = [crond, dotted, hidden, empty, nested, system, user, dotted_user, os.path.join(root, 'etc', 'cron.d')]
            with mock.patch.object(lc, 'logfunc') as log:
                headers, found, source = lc.linuxCrontabEntries.__wrapped__(FakeContext(paths, root, seeker))
        self.assertEqual(headers[0], ('File Modified', 'datetime'))
        self.assertEqual(len(headers), 18)
        self.assertEqual([(r[2], r[3], r[4]) for r in found[:9]],
                         [('cron.d', 1, 'Environment'), ('cron.d', 1, 'Comment'), ('System', 1, 'Comment'),
                          ('System', 2, 'Comment'), ('System', 3, 'Comment'), ('System', 4, 'Environment'),
                          ('System', 5, 'Job'), ('User', 1, 'Environment'), ('User', 1, 'Environment')])
        self.assertEqual(len(found), 22)
        self.assertEqual(found[6][11:13], ('root', 'cd /'))
        self.assertEqual({r[1] for r in found[2:7]} | {r[16] for r in found[2:7]}, {''})
        self.assertEqual(found[7][16:], ('', 'var/spool/cron/crontabs/.x'))
        self.assertEqual(found[8][16:], ('', 'var/spool/cron/crontabs/first.last'))
        known = found[9:]
        when = datetime(2026, 9, 29, 14, 8, 38, tzinfo=timezone.utc)
        self.assertEqual(known[4][:5], (when, 'Tue Sep 29 10:08:38 2026', 'User', 5, 'Environment'))
        self.assertEqual(known[7][11], 'parallels')
        self.assertEqual(known[4][11], '')
        self.assertEqual(known[0][11], '')
        self.assertEqual(known[7][16:], ('/home/parallels/crontab_known.txt', 'var/spool/cron/crontabs/parallels'))
        self.assertEqual(found[7][11:], ('', '', 'A', '1', 'A=1', '', 'var/spool/cron/crontabs/.x'))
        self.assertEqual(source.split('\n'), [dotted, crond, system, hidden, dotted_user, user])
        log.assert_called_once_with('Crontab Entries: 1 files in folders below the crontab folders, which cron does '
                                    'not read, 3 ' + lc.SKIPPED_NAME)

    def test_without_a_seeker_and_an_unreadable_file(self):
        with tempfile.TemporaryDirectory() as root:
            missing = os.path.join(root, 'etc', 'crontab')
            with mock.patch.object(lc, 'logfunc') as log:
                _headers, found, source = lc.linuxCrontabEntries.__wrapped__(FakeContext([missing], root))
        self.assertEqual((found, source), ([], ''))
        log.assert_called_once_with('Crontab Entries: 1 files that could not be read')


if __name__ == '__main__':
    unittest.main()
