"""Pin the four viminfo artifacts (scripts/artifacts/vimViminfo.py).

S1 is the lab VM's ~/.viminfo as Vim 9.1 wrote it after the first known session of ubuntu2604_arm64_viminfo, byte for
byte; everything in it was made for the known data.
"""
import os
import pathlib
import sys
import tempfile
import unittest
from collections import Counter
from datetime import datetime, timezone
from unittest import mock

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

# pylint: disable=wrong-import-position
from scripts.artifacts import vimViminfo as vv
# pylint: enable=wrong-import-position

ALPHA = '~/dleapp_vim_known/alpha.txt'
HEAD = b"# This viminfo file was generated by Vim 9.1.\n# You may edit it if you're careful!\n\n"
S1 = (HEAD + b"# Viminfo version\n|1,4\n\n# Value of 'encoding' when this file was written\n*encoding=utf-8\n\n\n"
      b"# hlsearch on (H) or off (h):\n~h\n# Last Search Pattern:\n~MSle0/line 5\n\n"
      b"# Last Substitute Search Pattern:\n~MSle0~&alpha\n\n# Last Substitute String:\n$ALPHA\n\n"
      b"# Command Line History (newest to oldest):\n:wq\n|2,0,1791109780,,\"wq\"\n:s/alpha/ALPHA/\n"
      b"|2,0,1791109780,,\"s/alpha/ALPHA/\"\n:set number\n|2,0,1791109780,,\"set number\"\n\n"
      b"# Search String History (newest to oldest):\n? alpha\n|2,1,1791109780,,\"alpha\"\n?/line 5\n"
      b"|2,1,1791109780,47,\"line 5\"\n\n# Expression History (newest to oldest):\n\n"
      b"# Input Line History (newest to oldest):\n\n# Debug Line History (newest to oldest):\n\n# Registers:\n"
      b"\"0\tLINE\t0\n\talpha line 5 dleappword5\n|3,0,0,1,1,0,1791109780,\"alpha line 5 dleappword5\"\n"
      b"\"\"a\tCHAR\t0\n\talpha\n|3,1,10,0,1,0,1791109780,\"alpha\"\n\n# File marks:\n"
      b"'B  3  0  ~/dleapp_vim_known/alpha.txt\n|4,66,3,0,1791109780,\"~/dleapp_vim_known/alpha.txt\"\n"
      b"'0  11  18  ~/dleapp_vim_known/alpha.txt\n|4,48,11,18,1791109780,\"~/dleapp_vim_known/alpha.txt\"\n\n"
      b"# Jumplist (newest first):\n-'  11  18  ~/dleapp_vim_known/alpha.txt\n"
      b"|4,39,11,18,1791109780,\"~/dleapp_vim_known/alpha.txt\"\n-'  3  0  ~/dleapp_vim_known/alpha.txt\n"
      b"|4,39,3,0,1791109780,\"~/dleapp_vim_known/alpha.txt\"\n-'  5  6  ~/dleapp_vim_known/alpha.txt\n"
      b"|4,39,5,6,1791109780,\"~/dleapp_vim_known/alpha.txt\"\n-'  1  0  ~/dleapp_vim_known/alpha.txt\n"
      b"|4,39,1,0,1791109780,\"~/dleapp_vim_known/alpha.txt\"\n\n"
      b"# History of marks within files (newest to oldest):\n\n> ~/dleapp_vim_known/alpha.txt\n"
      b"\t*\t1791109780\t0\n\t\"\t11\t18\n\t^\t11\t19\n\t.\t11\t0\n\t+\t11\t0\n\ta\t3\t0\n")
TWO_LINES = HEAD[:-1]     # the two comment lines without the empty line after them
T1 = 1791109780
WHEN = datetime(2026, 10, 4, 10, 29, 40, tzinfo=timezone.utc)


def records(data, counts=None):
    return vv.viminfo_records(data, Counter() if counts is None else counts)


def versioned(body, version=4, encoding=b'utf-8'):
    return TWO_LINES + b'|1,%d\n*encoding=%s\n' % (version, encoding) + body


class FakeContext:
    def __init__(self, paths, root):
        self.paths, self.root = paths, root

    def get_files_found(self):
        return self.paths

    def get_relative_path(self, path):
        return os.path.relpath(path, self.root).replace(os.sep, '/')


class KnownSessionTest(unittest.TestCase):
    def test_history(self):
        counts = Counter()
        got = records(S1, counts)
        self.assertEqual(got['history'], [
            (T1, 'Command line', 'wq', '', 24), (T1, 'Command line', 's/alpha/ALPHA/', '', 26),
            (T1, 'Command line', 'set number', '', 28), (T1, 'Search', 'alpha', '', 32),
            (T1, 'Search', 'line 5', '/', 34)])
        self.assertEqual((got['version'], got['encoding'], counts), (4, 'utf-8', Counter()))

    def test_registers(self):
        self.assertEqual(records(S1)['registers'], [
            (T1, '0', 'LINE', 0, ['alpha line 5 dleappword5'], False, False, 45),
            (T1, 'a', 'CHAR', 0, ['alpha'], True, False, 48)])

    def test_marks_and_jumps(self):
        self.assertEqual(records(S1)['marks'], [
            (T1, "'B", ALPHA, 3, 0, 52), (T1, "'0", ALPHA, 11, 18, 54), (T1, 'Jump', ALPHA, 11, 18, 58),
            (T1, 'Jump', ALPHA, 3, 0, 60), (T1, 'Jump', ALPHA, 5, 6, 62), (T1, 'Jump', ALPHA, 1, 0, 64)])

    def test_marks_within_files(self):
        self.assertEqual(records(S1)['files'], [
            (ALPHA, {'*': [(T1, 0)], '"': [(11, 18)], '^': [(11, 19)], '.': [(11, 0)], '+': [(11, 0)],
                     'a': [(3, 0)]}, 68)])

    def test_time(self):
        self.assertEqual(vv.utc(T1), WHEN)
        self.assertEqual((vv.utc(0), vv.utc(vv.TIME_MAX + 1)), ('', ''))


class BarLineTest(unittest.TestCase):
    def test_escapes(self):
        got = records(versioned(b'|2,0,5,,"say \\"hi\\" \\\\ and\\nmore"\n'))
        self.assertEqual(got['history'], [(5, 'Command line', 'say "hi" \\ and\nmore', '', 5)])

    def test_long_value_is_counted_in_bytes(self):
        text = ('日' * 300 + 'tail').encode('utf-8')
        quoted = b'"' + text + b'"'
        first, second = quoted[:500], quoted[500:]
        self.assertNotEqual(len(first.decode('utf-8', errors='ignore').encode('utf-8')), len(first))
        body = b'|2,0,7,,>%d\n|<%s\n|<%s\n' % (len(quoted), first, second)
        self.assertEqual(records(versioned(body))['history'], [(7, 'Command line', '日' * 300 + 'tail', '', 5)])

    def test_values_after_a_long_string(self):
        got = records(versioned(b'|3,0,10,1,2,0,9,>5\n|<"one","two"\n'))
        self.assertEqual(got['registers'], [(9, 'a', 'LINE', 0, ['one', 'two'], False, False, 5)])

    def test_continued_line_without_a_string(self):
        got = records(versioned(b'|4,66,3,>\n|<0,12,"f.txt"\n'))
        self.assertEqual(got['marks'], [(12, "'B", 'f.txt', 3, 0, 5)])

    def test_truncated_continuation(self):
        counts = Counter()
        got = records(versioned(b'|2,0,7,,>40\n|<"cut\n|2,0,8,,"next"\n'), counts)
        self.assertEqual(got['history'], [(8, 'Command line', 'next', '', 7)])
        self.assertEqual(counts, Counter({'history bar lines Vim would not accept, not reported': 1}))

    def test_search_separator_and_kinds(self):
        body = b'|2,1,5,63,"up"\n|2,1,5,,"none"\n|2,2,6,,"1+1"\n|2,3,7,,"typed"\n|2,4,8,,"cont"\n|2,0,9,47,"cmd"\n'
        self.assertEqual([(h[1], h[2], h[3]) for h in records(versioned(body))['history']], [
            ('Search', 'up', '?'), ('Search', 'none', ''), ('Expression', '1+1', ''), ('Input line', 'typed', ''),
            ('Debug line', 'cont', ''), ('Command line', 'cmd', '')])

    def test_history_lines_vim_would_not_accept(self):
        counts = Counter()
        body = b'|2,5,1,,"kind"\n|2,0,1,,""\n|2,0,,,"notime"\n|2,0,1,"x","y"\n|2,0,1\n|9,1,2\n|2,0,3,,"kept"\n'
        self.assertEqual([h[2] for h in records(versioned(body), counts)['history']], ['kept'])
        self.assertEqual(counts, Counter({'history bar lines Vim would not accept, not reported': 5,
                                          'bar lines of a type Vim 9.1 does not define, passed over': 1}))

    def test_register_names_types_and_flags(self):
        body = (b'|3,1,0,0,1,0,5,"zero"\n|3,2,35,2,2,7,6,"ab","cd"\n|3,3,36,1,1,0,7,"gone"\n|3,0,37,1,1,0,8,"star"\n'
                b'|3,0,1,1,0,0,9\n')
        self.assertEqual(records(versioned(body))['registers'], [
            (5, '0', 'CHAR', 0, ['zero'], True, False, 5), (6, 'z', 'BLOCK', 7, ['ab', 'cd'], False, True, 6),
            (7, '-', 'LINE', 0, ['gone'], True, True, 7), (8, '(register 37)', 'LINE', 0, ['star'], False, False, 8),
            (9, '1', 'LINE', 0, [], False, False, 9)])

    def test_register_lines_vim_would_not_accept(self):
        counts = Counter()
        body = b'|3,0,33,2,1,-1,5,""\n|3,0,1,3,1,0,5,"type"\n|3,0,1,1,2,0,5,"short"\n|3,0,1,1\n'
        self.assertEqual(records(versioned(body), counts)['registers'], [])
        self.assertEqual(counts, Counter({'register bar lines Vim would not accept, not reported': 4}))

    def test_mark_lines_vim_would_not_accept(self):
        counts = Counter()
        body = b'|4,97,1,0,5,"lower"\n|4,66,0,0,5,"line0"\n|4,66,1,0,5\n|4,57,2,3,0,"nine"\n'
        self.assertEqual(records(versioned(body), counts)['marks'], [(0, "'9", 'nine', 2, 3, 8)])
        self.assertEqual(counts, Counter({'mark bar lines Vim would not accept, not reported': 3}))

    def test_version_after_the_encoding_is_not_used(self):
        data = HEAD + b'*encoding=utf-8\n|1,4\n:old\n|2,0,5,,"new"\n'
        got = records(data)
        self.assertEqual((got['version'], [h[2] for h in got['history']]), (0, ['old', 'new']))


class OlderLinesTest(unittest.TestCase):
    OLD = (TWO_LINES + b"*encoding=latin1\n:first cmd\n?/find me\n? plain\n=2*3\n@answer\n\"\"a@\tCHAR\t0\n\tyanked\n"
           b"\"b\tBLOCK\t4\n\tab\n\tcd\n\"!\tLINE\t0\n\tbad\n'A  7  2  /tmp/a.txt\n-'  9  0  /tmp/b.txt\n'a  1  1  no\n"
           b"> /tmp/a.txt\n\t\"\t7\t2\n")

    def test_read_when_the_file_has_no_version(self):
        counts = Counter()
        got = records(self.OLD, counts)
        self.assertEqual(got['history'], [
            (0, 'Command line', 'first cmd', '', 4), (0, 'Search', 'find me', '/', 5), (0, 'Search', 'plain', '', 6),
            (0, 'Expression', '2*3', '', 7), (0, 'Input or debug line', 'answer', '', 8)])
        self.assertEqual(got['registers'], [(0, 'a', 'CHAR', 0, ['yanked'], True, True, 9),
                                            (0, 'b', 'BLOCK', 4, ['ab', 'cd'], False, False, 11)])
        self.assertEqual(got['marks'], [(0, "'A", '/tmp/a.txt', 7, 2, 16), (0, 'Jump', '/tmp/b.txt', 9, 0, 17)])
        self.assertEqual(got['files'], [('/tmp/a.txt', {'"': [(7, 2)]}, 19)])
        self.assertEqual((got['version'], got['encoding']), (0, 'latin1'))
        self.assertEqual(counts, Counter({'register lines with a name Vim would not accept, not reported': 1}))

    def test_each_kind_stops_at_its_version(self):
        body = self.OLD[len(TWO_LINES):].replace(b'*encoding=latin1\n', b'')
        for version, kept in ((1, (5, 2, 2)), (2, (0, 2, 2)), (3, (0, 0, 2)), (4, (0, 0, 0))):
            got = records(versioned(body, version))
            self.assertEqual((len(got['history']), len(got['registers']), len(got['marks'])), kept, version)
            self.assertEqual(len(got['files']), 1)

    def test_long_form_and_ctrl_v(self):
        long_text = b'x' * 300
        data = HEAD + b':\x16303\n<' + long_text + b'\n:a\x16nb\x16\x16c\n'
        self.assertEqual([h[2] for h in records(data)['history']], ['x' * 300, 'a\nb\x16c'])

    def test_long_search_entry_keeps_its_text(self):
        data = HEAD + b'? \x16303\n<' + b'y' * 300 + b'\n?/short\n'
        self.assertEqual([(h[2], h[3]) for h in records(data)['history']], [('y' * 300, ''), ('short', '/')])
        data = versioned(b'? \x16303\n<' + b'|' * 300 + b'\n|2,1,5,,"real"\n')
        self.assertEqual([h[2] for h in records(data)['history']], ['real'])

    def test_long_form_is_stepped_over_when_bar_lines_are_used(self):
        data = versioned(b':\x16303\n<' + b':' * 300 + b'\n|2,0,5,,"real"\n\'B  1  0  \x1640\n<|4,66,9,9,9,"fake"\n')
        got = records(data)
        self.assertEqual(([h[2] for h in got['history']], got['marks']), (['real'], []))

    def test_long_register_line_in_the_older_form(self):
        data = HEAD + b'"a\tLINE\t0\n\t\x16303\n<' + b'z' * 300 + b'\n\tshort\n<stray\n\tlast\n:cmd\n'
        got = records(data)
        self.assertEqual(got['registers'], [(0, 'a', 'LINE', 0, ['z' * 300, 'short', 'last'], False, False, 4)])
        self.assertEqual([h[2] for h in got['history']], ['cmd'])

    def test_latin1_and_bad_bytes(self):
        got = records(versioned(b'|2,0,5,,"caf\xe9"\n', encoding=b'latin1'))
        self.assertEqual(got['history'][0][2], 'caf\xe9')
        got = records(versioned(b'|2,0,5,,"caf\xe9"\n'))
        self.assertEqual(got['history'][0][2], 'caf\\xe9')
        got = records(versioned(b'|2,0,5,,"x"\n', encoding=b'no-such-encoding'))
        self.assertEqual(got['encoding'], 'latin-1')

    def test_carriage_returns(self):
        old = records(self.OLD.replace(b'\n', b'\r\n'))
        self.assertEqual(([h[2] for h in old['history']], old['registers'][1][4], old['marks'][0][2]),
                         (['first cmd', 'find me', 'plain', '2*3', 'answer'], ['ab', 'cd'], '/tmp/a.txt'))
        got = records(S1.replace(b'\n', b'\r\n'))
        self.assertEqual((len(got['history']), len(got['registers']), len(got['marks']), got['files'][0][0]),
                         (5, 2, 6, ALPHA))

    def test_marks_within_files(self):
        counts = Counter()
        data = versioned(b'>  /a b.txt  \n\t*\t77\t0\n\t+\t1\t2\n\t+\t3\t4\n\tb\tx\ty\n\tc\t5\n#c\n> /n.txt\n')
        self.assertEqual(records(data, counts)['files'], [
            ('/a b.txt', {'*': [(77, 0)], '+': [(1, 2), (3, 4)], 'c': [(5, 0)]}, 5), ('/n.txt', {}, 12)])
        self.assertEqual(counts, Counter({'mark lines within a file whose numbers do not read, passed over': 1}))


class ArtifactTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()  # pylint: disable=consider-using-with
        self.root = self.tmp.name
        self.logged = []
        patcher = mock.patch.object(vv, 'logfunc', self.logged.append)
        patcher.start()
        self.addCleanup(patcher.stop)
        self.paths = []

    def tearDown(self):
        self.tmp.cleanup()

    def add(self, relative, data):
        path = os.path.join(self.root, *relative.split('/'))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'wb') as handle:
            handle.write(data)
        self.paths.append(path)
        return path

    def test_rows(self):
        one = self.add('home/u/.viminfo', S1)
        self.add('home/w/.viminfo', b'not a viminfo file\n')
        empty = self.add('Users/x/_viminfo', HEAD + b'*encoding=utf-8\n')
        self.add('home/y/.viminfo', HEAD)
        folder = os.path.join(self.root, 'home', 'dir', '.viminfo')
        os.makedirs(folder)
        self.paths.append(folder)
        context = FakeContext(self.paths, self.root)
        headers, rows, source = vv.vimHistory.__wrapped__(context)
        self.assertEqual(headers, (('Time (UTC)', 'datetime'), 'History', 'Entry', 'Search Separator', 'Line',
                                   'Source File'))
        self.assertEqual(rows[0], (WHEN, 'Command line', 'wq', '', 24, 'home/u/.viminfo'))
        self.assertEqual((len(rows), rows[4][1:4], source), (5, ('Search', 'line 5', '/'), one))
        headers, rows, source = vv.vimRegisters.__wrapped__(context)
        self.assertEqual(headers, (('Time (UTC)', 'datetime'), 'Register', 'Type', 'Text', 'Lines', 'Block Width',
                                   'Unnamed Register', 'Last Executed', 'Line', 'Source File'))
        self.assertEqual(rows, [(WHEN, '0', 'LINE', 'alpha line 5 dleappword5', 1, 0, '', '', 45, 'home/u/.viminfo'),
                                (WHEN, 'a', 'CHAR', 'alpha', 1, 0, 'Yes', '', 48, 'home/u/.viminfo')])
        headers, rows, source = vv.vimFileMarks.__wrapped__(context)
        self.assertEqual(headers, (('Time (UTC)', 'datetime'), 'Mark', 'File', 'Line Number', 'Column', 'Line',
                                   'Source File'))
        self.assertEqual((len(rows), rows[0], rows[2][1]),
                         (6, (WHEN, "'B", ALPHA, 3, 0, 52, 'home/u/.viminfo'), 'Jump'))
        headers, rows, source = vv.vimFileHistory.__wrapped__(context)
        self.assertEqual(headers, (('Last Used (UTC)', 'datetime'), 'File', 'Cursor', 'Last Insert', 'Last Change',
                                   'Change List', 'Named Marks', 'Line', 'Source File'))
        self.assertEqual(rows, [(WHEN, ALPHA, '11:18', '11:19', '11:0', '11:0', 'a 3:0', 68, 'home/u/.viminfo')])
        self.assertEqual(source, one)
        self.assertNotIn(empty, source)
        self.assertEqual(self.logged, [
            f'{name}: 2 files with neither an *encoding= line nor a version line, not read'
            for name in ('Vim History', 'Vim Registers', 'Vim File Marks and Jumps', 'Vim Marks Within Files')])

    def test_multi_line_register_and_blank_time(self):
        self.add('home/u/.viminfo', versioned(b'|3,0,11,1,2,0,0,"one","two"\n> /f\n\t"\t1\t0\n\t"\t9\t4\n\tz\t2\t3\n'
                                              b'\ta\t5\t6\n\tA\t7\t8\n'))
        context = FakeContext(self.paths, self.root)
        self.assertEqual(vv.vimRegisters.__wrapped__(context)[1],
                         [('', 'b', 'LINE', 'one\ntwo', 2, 0, '', '', 5, 'home/u/.viminfo')])
        self.assertEqual(vv.vimFileHistory.__wrapped__(context)[1], [('', '/f', '9:4', '', '', '', 'a 5:6; z 2:3', 6,
                                                                      'home/u/.viminfo')])

    def test_header_comment_in_another_language(self):
        self.add('home/u/.viminfo', S1.replace(b'# This viminfo file was generated by Vim 9.1.',
                                               '# Ce fichier viminfo a \u00e9t\u00e9 g\u00e9n\u00e9r\u00e9 par Vim 9.1.'.encode()))
        self.assertEqual(len(vv.vimHistory.__wrapped__(FakeContext(self.paths, self.root))[1]), 5)
        self.assertEqual(self.logged, [])

    def test_unreadable_file_is_counted(self):
        self.add('home/u/.viminfo', S1)
        with mock.patch('builtins.open', side_effect=OSError('denied')):
            _h, rows, source = vv.vimHistory.__wrapped__(FakeContext(self.paths, self.root))
        self.assertEqual((rows, source), ([], ''))
        self.assertEqual(self.logged, ['Vim History: 1 files that could not be read'])


if __name__ == '__main__':
    unittest.main()
