"""Network profiles NetworkManager and netplan keep on a Linux system, for DLEAPP.

Author: @AlexisBrignoni, Claude.
"""

__artifacts_v2__ = {
    "networkManagerProfiles": {
        "name": "NetworkManager Connection Profiles",
        "description": "Connection profiles NetworkManager keeps as key files, one row per file: the profile's "
                       "name, identifier and type, and for a Wi-Fi profile the network name and the key stored "
                       "with it.",
        "author": "@AlexisBrignoni, Claude",
        "creation_date": "2026-10-10",
        "last_update_date": "2026-10-10",
        "requirements": "PyYAML",
        "category": "Networks (Linux)",
        "notes": "Reads each file in a NetworkManager system-connections folder as a key file: groups in square "
                 "brackets, key=value lines, lines beginning with # as comments, the last value of a repeated key, "
                 "and the escapes for space, new line, tab, carriage return and backslash replaced in a value "
                 "(Reference: GLib 2.86.0, commit e33be08bda99f453e497064e9e021d6306bbeb7d, "
                 "https://github.com/GNOME/glib, 'glib/gkeyfile.c' lines 113 to 127 and 153 to 156). One row is "
                 "reported per file that has a connection group. Profile Name, UUID, Type, Interface and Autoconnect "
                 "are the id, uuid, type, interface-name and autoconnect keys of that group as written, and "
                 "Timestamp (UTC) is its timestamp key, which NetworkManager defines as the time in seconds since "
                 "the Unix Epoch that the connection was last successfully fully activated (Reference: "
                 "NetworkManager 1.54.3, commit 8caccc6bed0b56528ef3d880af1c217bb8d24419, "
                 "https://github.com/NetworkManager/NetworkManager, 'src/libnm-core-impl/nm-setting-connection.c' "
                 "lines 2864 to 2865); 0 and a value that is not a number give an empty cell. A profile file need "
                 "not hold that key, and the NetworkManager Last Activation Times artifact reads the store "
                 "NetworkManager keeps those times in. SSID and Hidden are the ssid and hidden keys of the wifi "
                 "group, Key Management and Pre-Shared Key the key-mgmt and psk keys of the wifi-security group, or "
                 "of the groups named 802-11-wireless and 802-11-wireless-security when the file uses those names, "
                 "and IPv4 Method and IPv6 Method the method keys of the ipv4 and ipv6 groups. A key that is absent "
                 "gives an empty cell. Other Groups names the groups the row does not show. The row shows only the "
                 "named keys of the groups it reads; the other keys of every group, which can include other secrets, "
                 "are in the file. A file with no connection group is counted in the run log and not reported. "
                 "ubuntu2604_arm64_nm_a and ubuntu2604_arm64_nm_b are known data from a VM running NetworkManager "
                 "1.54.3 and netplan 1.2 with no Wi-Fi device: with nmcli two Wi-Fi profiles were added, dleapp "
                 "known open with the network name dleapp known ssid one and no security, and dleapp known psk with "
                 "dleapp known ssid two and a made-up WPA passphrase, the first was then set to hidden, the files "
                 "were captured (a), both profiles were deleted and the files were captured again (b). On a the 5 "
                 "rows are the two test profiles, two wired profiles and the loopback profile, the same five files "
                 "and names that nmcli listed at that moment, with the same identifiers on the three files that hold "
                 "a uuid key, all under /run/NetworkManager; the folder under /etc/NetworkManager is empty. The test "
                 "and wired files there are named netplan- and the loopback file holds a group that marks it as "
                 "generated by NetworkManager. The two test rows hold the names and network names given to nmcli, "
                 "Type wifi, Autoconnect false, Hidden true on the first only, and Key Management wpa-psk with the "
                 "made-up passphrase in Pre-Shared Key on the second only. Timestamp (UTC) and UUID are filled on "
                 "the loopback row and UUID on the two test rows; the wired files hold neither key. On b the 3 rows "
                 "are the wired and loopback profiles, and SSID, Hidden, Key Management, Pre-Shared Key and "
                 "Autoconnect are empty on all 3. NetworkManager treats the /run folder as runtime-only storage "
                 "('src/core/settings/plugins/keyfile/nms-keyfile-utils.h' line 17). An image of a powered-off "
                 "system was not tested; on a system like this one the profiles kept on disk are the files the "
                 "Netplan Network Definitions artifact reads. Not exercised on real data: a profile under "
                 "/etc/NetworkManager, a profile that was activated over Wi-Fi, the 802-11-wireless group names, a "
                 "network name written as a list of byte values or holding a semicolon, which NetworkManager writes "
                 "with a backslash before it ('src/libnm-core-impl/nm-keyfile.c' lines 2764 to 2774), both shown as "
                 "written, and VPN, WireGuard and 802.1X profiles, whose own keys are not shown; the 802-11-wireless "
                 "group names were tested with constructed input. A row shows that the profile exists, not that the "
                 "system connected to that network.",
        "paths": ("*/NetworkManager/system-connections/*",),
        "output_types": "standard",
        "artifact_icon": "wifi",
        "sample_data": {
            "honeynet_fc7_debian5": "Debian 5.0.7 i386 | 0 rows (no member matches the declared paths)",
            "rocky98_arm64_known": "Rocky Linux 9.8 aarch64 | 0 rows (no member matches the declared paths)",
            "ubuntu2604_arm64_nm_a": "Ubuntu 26.04 LTS aarch64, NetworkManager 1.54.3 | 5 rows",
            "ubuntu2604_arm64_nm_b": "Ubuntu 26.04 LTS aarch64, NetworkManager 1.54.3 | 3 rows",
            "ubuntu2604_arm64_triage": "Ubuntu 26.04 LTS aarch64 | 0 rows (no member matches the declared paths)",
        },
    },
    "netplanNetworks": {
        "name": "Netplan Network Definitions",
        "description": "Network definitions in netplan's YAML files, one row per device and, for Wi-Fi, per "
                       "access point: the network name, the key stored with it, and the name and identifier "
                       "NetworkManager gave the profile when it wrote the file.",
        "author": "@AlexisBrignoni, Claude",
        "creation_date": "2026-10-10",
        "last_update_date": "2026-10-10",
        "requirements": "PyYAML",
        "category": "Networks (Linux)",
        "notes": "Reads netplan's YAML files in /etc/netplan, /run/netplan and /lib/netplan with PyYAML's base "
                 "loader, which keeps every value as the text written, so a value such as an unquoted password of "
                 "digits is not turned into a number. A file holds a network mapping with one mapping per device "
                 "type, each a mapping of device IDs (Reference: netplan 1.2, commit "
                 "b0fdccf2d80b256da401f665b8c977466eb2a61c, https://github.com/canonical/netplan, "
                 "'doc/netplan-yaml.md' lines 3 to 22). One row is reported per device and, for a device with access "
                 "points, per access point, the keys of the access-points mapping being the network names (lines "
                 "1176 to 1181). Device Type is the device type key and Device ID the device's key. Renderer is the "
                 "device's renderer key or, when it has none, the renderer key of its device type or, failing that, "
                 "of the top of the same file (lines 28 to 30 and 304 to 309); a renderer set in another file is not "
                 "shown, so an empty cell does not mean the default. NetworkManager Name and NetworkManager UUID are "
                 "the name and uuid of the networkmanager mapping, which the reference describes as the display name "
                 "and the identifier generated by NetworkManager (lines 2171 to 2183), taken from the access point "
                 "when it has one and from the device otherwise. SSID is the access point's key, Hidden its hidden "
                 "key (line 1222), Key Management the key-management of its auth mapping (line 910) and Password the "
                 "password of that mapping or, when it has none, the access point's own password key (lines 1183 to "
                 "1196). MAC Match is the macaddress of the device's match mapping (lines 86 and 99), Set Name, "
                 "DHCP4 and DHCP6 the set-name, dhcp4 and dhcp6 keys (lines 151, 317 and 321) and Addresses the "
                 "addresses key, its items joined with ' | '. A value is shown as written and an absent key as an "
                 "empty cell. Other Keys names the keys the row reads nothing from: those of the device, those of "
                 "the access point after the words access point, and, after the mapping's name, the keys of a match, "
                 "auth or networkmanager mapping other than the ones shown; their values are in the file. A file "
                 "that is not YAML is counted in the run log and not reported. ubuntu2604_arm64_nm_a and "
                 "ubuntu2604_arm64_nm_b are known data from a VM running NetworkManager 1.54.3 and netplan 1.2 with "
                 "no Wi-Fi device: with nmcli two Wi-Fi profiles were added, dleapp known open with the network name "
                 "dleapp known ssid one and no security, and dleapp known psk with dleapp known ssid two and a "
                 "made-up WPA passphrase, the first was then set to hidden, the files were captured (a), both "
                 "profiles were deleted and the files were captured again (b). On a the 4 rows are two wired devices "
                 "from the two files the system already had and the two test profiles, each in a file NetworkManager "
                 "wrote, named 90-NM- and the profile's identifier: Device Type wifis, Renderer NetworkManager, the "
                 "profile names and network names given to nmcli, Hidden true on the first only, and Key Management "
                 "psk with the made-up passphrase in Password on the second only. The name and identifier on both "
                 "rows are the ones nmcli listed. In the capture's listing the first profile's file has the modified "
                 "time of the step that set it to hidden and the second profile's file that of the step that added "
                 "it, each to the same second. Other Keys names the passthrough mapping of the access point's "
                 "networkmanager mapping on both test rows and is empty on the wired rows, Addresses is empty on all "
                 "4 rows, DHCP4 held one value, true, on all 4 rows, and Renderer is empty on the two wired rows. On "
                 "b the 2 rows are the wired devices: the two test files are gone, and Renderer, NetworkManager "
                 "Name, NetworkManager UUID, SSID, Hidden, Key Management, Password, Addresses and Other Keys are "
                 "empty on both rows, and Device Type and DHCP4 each held one value on both rows. Between a and b "
                 "both earlier files got a new modified time and one was rewritten with the same settings in a "
                 "different layout; the rows are the same in both. Not exercised on real data: device types other "
                 "than ethernets and wifis, a device with several access points, a password outside an auth mapping, "
                 "static addresses, enterprise authentication, whose keys are named in Other Keys, a renderer set "
                 "for a device type, values written without quotes that YAML would read as numbers or booleans, and "
                 "files under /run/netplan and /lib/netplan; all of these but the last were tested with constructed "
                 "input. A row shows that the network is defined on the system, not that the system connected to it.",
        "paths": ("*/etc/netplan/*.yaml", "*/run/netplan/*.yaml", "*/lib/netplan/*.yaml"),
        "output_types": "standard",
        "artifact_icon": "wifi",
        "sample_data": {
            "honeynet_fc7_debian5": "Debian 5.0.7 i386 | 0 rows (no member matches the declared paths)",
            "rocky98_arm64_known": "Rocky Linux 9.8 aarch64 | 0 rows (no member matches the declared paths)",
            "ubuntu2604_arm64_nm_a": "Ubuntu 26.04 LTS aarch64, netplan 1.2 | 4 rows",
            "ubuntu2604_arm64_nm_b": "Ubuntu 26.04 LTS aarch64, netplan 1.2 | 2 rows",
            "ubuntu2604_arm64_triage": "Ubuntu 26.04 LTS aarch64 | 0 rows (no member matches the declared paths)",
        },
    },
    "networkManagerTimestamps": {
        "name": "NetworkManager Last Activation Times",
        "description": "The time NetworkManager recorded for the last activation of each connection profile, and "
                       "the access point addresses it recorded for the profile, one row per profile identifier.",
        "author": "@AlexisBrignoni, Claude",
        "creation_date": "2026-10-10",
        "last_update_date": "2026-10-10",
        "requirements": "PyYAML",
        "category": "Networks (Linux)",
        "notes": "Reads the two key files NetworkManager keeps in its state folder, /var/lib/NetworkManager: "
                 "timestamps, group timestamps, and seen-bssids, group seen-bssids (Reference: NetworkManager "
                 "1.54.3, commit 8caccc6bed0b56528ef3d880af1c217bb8d24419, "
                 "https://github.com/NetworkManager/NetworkManager, 'src/core/settings/nm-settings.c' lines 4068 to "
                 "4077), each keyed by the connection's uuid ('src/core/settings/nm-settings-connection.c' lines "
                 "2372 to 2376 and 2426). One row is reported per identifier found in either file. Last Activated "
                 "(UTC) is the value in timestamps, which NetworkManager writes as a decimal number when it updates "
                 "a connection's timestamp ('src/core/settings/nm-settings-connection.c' lines 2349 to 2377), the "
                 "time in seconds since the Unix Epoch that the connection was last successfully fully activated "
                 "('src/libnm-core-impl/nm-setting-connection.c' lines 2864 to 2865); 0 and a value that is not a "
                 "number give an empty cell. Seen BSSIDs is the list in seen-bssids, its items joined with ' | '. "
                 "Profile Name is the name of the profile with that identifier, looked up in the NetworkManager "
                 "profile files and the files of /etc/netplan found in the extraction, and is empty when none holds "
                 "it. Source File names the file or files that hold the identifier. ubuntu2604_arm64_nm_a and "
                 "ubuntu2604_arm64_nm_b are known data from a VM running NetworkManager 1.54.3 and netplan 1.2 with "
                 "no Wi-Fi device: with nmcli two Wi-Fi profiles were added, dleapp known open with the network name "
                 "dleapp known ssid one and no security, and dleapp known psk with dleapp known ssid two and a "
                 "made-up WPA passphrase, the first was then set to hidden, the files were captured (a), both "
                 "profiles were deleted and the files were captured again (b). Both captures give the same 2 rows. "
                 "One identifier is the loopback profile's: Profile Name lo, and Last Activated (UTC) equal to the "
                 "timestamp key in that profile's own file. The other has no Profile Name, no profile file in the "
                 "capture holding that identifier; nmcli's own listing in the capture gives it to one of the wired "
                 "profiles, whose file holds no uuid key. The two test profiles, never activated, have no row. Seen "
                 "BSSIDs is empty on both rows, the seen-bssids file being empty, so that column was tested with "
                 "constructed input only, and Source File held one value on both rows. Not exercised on real data: a "
                 "profile that connected over Wi-Fi. A time is the last activation NetworkManager recorded for the "
                 "profile, which it updates periodically while the connection is active "
                 "('src/libnm-core-impl/nm-setting-connection.c' lines 2867 to 2869), not a history of connections.",
        "paths": ("*/var/lib/NetworkManager/timestamps", "*/var/lib/NetworkManager/seen-bssids",
                  "*/NetworkManager/system-connections/*", "*/etc/netplan/*.yaml"),
        "output_types": "standard",
        "artifact_icon": "clock",
        "sample_data": {
            "honeynet_fc7_debian5": "Debian 5.0.7 i386 | 0 rows (no member matches the declared paths)",
            "rocky98_arm64_known": "Rocky Linux 9.8 aarch64 | 0 rows (no member matches the declared paths)",
            "ubuntu2604_arm64_nm_a": "Ubuntu 26.04 LTS aarch64, NetworkManager 1.54.3 | 2 rows",
            "ubuntu2604_arm64_nm_b": "Ubuntu 26.04 LTS aarch64, NetworkManager 1.54.3 | 2 rows",
            "ubuntu2604_arm64_triage": "Ubuntu 26.04 LTS aarch64 | 0 rows (no member matches the declared paths)",
        },
    },
}

import os
from collections import Counter
from datetime import datetime, timedelta, timezone

import yaml

from scripts.ilapfuncs import artifact_processor, logfunc

_EPOCH = datetime(1970, 1, 1, tzinfo=timezone.utc)
_ESCAPES = {'s': ' ', 'n': '\n', 't': '\t', 'r': '\r', '\\': '\\'}
# netplan's device types, the mappings under "network"
DEVICE_TYPES = ('bonds', 'bridges', 'dummy-devices', 'ethernets', 'modems', 'tunnels', 'virtual-ethernets', 'vlans',
                'vrfs', 'wifis', 'nm-devices')
_DEVICE_SHOWN = ('renderer', 'networkmanager', 'access-points', 'match', 'set-name', 'dhcp4', 'dhcp6', 'addresses')
_POINT_SHOWN = ('networkmanager', 'hidden', 'auth', 'password')
# the keys read inside a mapping the row shows part of
_INSIDE_SHOWN = {'match': ('macaddress',), 'networkmanager': ('name', 'uuid'), 'auth': ('key-management', 'password')}
_GROUPS_SHOWN = ('connection', 'wifi', '802-11-wireless', 'wifi-security', '802-11-wireless-security', 'ipv4', 'ipv6')


def utc(text):
    """The UTC time of a count of seconds since 1970 written in decimal digits, or '' for anything else and for 0,
    which NetworkManager uses for a profile that was never activated."""
    text = text.strip()
    if not text.isascii() or not text.isdigit() or int(text) == 0:
        return ''
    try:
        return _EPOCH + timedelta(seconds=int(text))
    except OverflowError:
        return ''


def key_file(data):
    """The groups of a key file: group name to a dict of key to value, a later value of a key replacing an earlier
    one, and the number of non-empty lines that are neither a comment, a group header nor a key with a value. A
    value has its leading white space removed and the escapes for space, new line, tab, carriage return and
    backslash replaced."""
    groups, current, skipped = {}, None, 0
    for raw in data.decode('utf-8', 'backslashreplace').split('\n'):
        line = raw.rstrip('\r')
        if not line.strip() or line.startswith('#'):
            continue
        if line.startswith('[') and line.rstrip().endswith(']'):
            current = groups.setdefault(line.rstrip()[1:-1], {})
            continue
        key, separator, value = line.partition('=')
        if not separator or current is None or not key.strip():
            skipped += 1
            continue
        current[key.strip()] = _unescape(value.lstrip())
    return groups, skipped


def _unescape(value):
    out, index = [], 0
    while index < len(value):
        char = value[index]
        if char == '\\' and index + 1 < len(value) and value[index + 1] in _ESCAPES:
            out.append(_ESCAPES[value[index + 1]])
            index += 2
        else:
            out.append(char)
            index += 1
    return ''.join(out)


def profile_row(groups):
    """(timestamp, name, uuid, type, interface, ssid, hidden, key management, pre-shared key, autoconnect, ipv4
    method, ipv6 method, other groups) for a profile's key file groups, or None when it has no connection group."""
    connection = groups.get('connection')
    if connection is None:
        return None
    wifi = groups.get('wifi', groups.get('802-11-wireless', {}))
    security = groups.get('wifi-security', groups.get('802-11-wireless-security', {}))
    return (utc(connection.get('timestamp', '')), connection.get('id', ''), connection.get('uuid', ''),
            connection.get('type', ''), connection.get('interface-name', ''), wifi.get('ssid', ''),
            wifi.get('hidden', ''), security.get('key-mgmt', ''), security.get('psk', ''),
            connection.get('autoconnect', ''), groups.get('ipv4', {}).get('method', ''),
            groups.get('ipv6', {}).get('method', ''),
            ', '.join(name for name in groups if name not in _GROUPS_SHOWN))


def _read(path):
    with open(path, 'rb') as handle:
        return handle.read()


def _files(context, *suffixes):
    """The found files, sorted, that are not folders and whose evidence path ends with or holds one of the texts."""
    picked = []
    for path in sorted(str(p) for p in context.get_files_found() if not os.path.isdir(p)):
        relative = context.get_relative_path(path).replace('\\', '/')
        if any(text in '/' + relative for text in suffixes):
            picked.append(path)
    return picked


def _log(label, counts):
    if counts:
        logfunc(label + ': ' + ', '.join(f'{count} {kind}' for kind, count in sorted(counts.items())))


@artifact_processor
def networkManagerProfiles(context):
    data_headers = (('Timestamp (UTC)', 'datetime'), 'Profile Name', 'UUID', 'Type', 'Interface', 'SSID', 'Hidden',
                    'Key Management', 'Pre-Shared Key', 'Autoconnect', 'IPv4 Method', 'IPv6 Method',
                    'Other Groups', 'Source File')
    data_list, read, counts = [], [], Counter()
    for path in _files(context, '/NetworkManager/system-connections/'):
        try:
            groups, skipped = key_file(_read(path))
        except OSError:
            counts['files that could not be read'] += 1
            continue
        row = profile_row(groups)
        if row is None:
            counts['files with no connection group, not reported'] += 1
            continue
        if skipped:
            counts['lines that are no group and no key, skipped'] += skipped
        data_list.append(row + (context.get_relative_path(path),))
        read.append(path)
    _log('NetworkManager Connection Profiles', counts)
    return data_headers, data_list, '\n'.join(read)


def _text(value):
    """A YAML value as text: a scalar as written, a sequence joined with ' | ', a mapping as its keys."""
    if isinstance(value, (list, tuple)):
        return ' | '.join(_text(item) for item in value)
    if isinstance(value, dict):
        return ' | '.join(str(key) for key in value)
    return '' if value is None else str(value)


def _mapping(value):
    return value if isinstance(value, dict) else {}


def _unshown(mapping, shown, prefix=''):
    """The names of the keys of a device or access point that the row reads nothing from: a key not in shown, and
    for a mapping the row reads part of, each of its other keys after the mapping's name."""
    names = []
    for key, value in mapping.items():
        if key not in shown:
            names.append(prefix + str(key))
        elif key in _INSIDE_SHOWN:
            names.extend(f'{prefix}{key} {inner}' for inner in _mapping(value) if inner not in _INSIDE_SHOWN[key])
    return names


def load_netplan(data):
    """A netplan file's document with every scalar kept as the text written, which the base loader does: the safe
    loader would turn an unquoted password of digits or a network name such as No into another value."""
    return yaml.load(data, Loader=yaml.BaseLoader)


def netplan_rows(document):
    """(device type, device id, renderer, NetworkManager name, NetworkManager uuid, ssid, hidden, key management,
    password, MAC match, set name, dhcp4, dhcp6, addresses, other keys) for each device of a netplan document and,
    for a device with access points, for each of them. A renderer key directly under a device type is that type's
    renderer, not a device."""
    network = _mapping(_mapping(document).get('network'))
    rows = []
    for kind in DEVICE_TYPES:
        section = _mapping(network.get(kind))
        type_renderer = section.get('renderer') if not isinstance(section.get('renderer'), dict) else None
        for device_id, device in section.items():
            if device_id == 'renderer' and not isinstance(device, dict):
                continue
            device = _mapping(device)
            backend = _mapping(device.get('networkmanager'))
            renderer = device.get('renderer', type_renderer if type_renderer is not None else network.get('renderer'))
            common = (_text(renderer),)
            tail = (_text(_mapping(device.get('match')).get('macaddress')), _text(device.get('set-name')),
                    _text(device.get('dhcp4')), _text(device.get('dhcp6')), _text(device.get('addresses')))
            other = _unshown(device, _DEVICE_SHOWN)
            points = _mapping(device.get('access-points'))
            if not points:
                rows.append((kind, _text(device_id)) + common
                            + (_text(backend.get('name')), _text(backend.get('uuid')), '', '', '', '')
                            + tail + (', '.join(other),))
            for ssid, point in points.items():
                point = _mapping(point)
                own = _mapping(point.get('networkmanager'))
                auth = _mapping(point.get('auth'))
                password = auth['password'] if 'password' in auth else point.get('password')
                rows.append((kind, _text(device_id)) + common
                            + (_text(own.get('name', backend.get('name'))), _text(own.get('uuid', backend.get('uuid'))),
                               _text(ssid), _text(point.get('hidden')), _text(auth.get('key-management')),
                               _text(password))
                            + tail + (', '.join(other + _unshown(point, _POINT_SHOWN, 'access point ')),))
    return rows


@artifact_processor
def netplanNetworks(context):
    data_headers = ('Device Type', 'Device ID', 'Renderer', 'NetworkManager Name', 'NetworkManager UUID', 'SSID',
                    'Hidden', 'Key Management', 'Password', 'MAC Match', 'Set Name', 'DHCP4', 'DHCP6', 'Addresses',
                    'Other Keys', 'Source File')
    data_list, read, counts = [], [], Counter()
    for path in _files(context, '/netplan/'):
        try:
            document = load_netplan(_read(path))
        except OSError:
            counts['files that could not be read'] += 1
            continue
        except yaml.YAMLError:
            counts['files that are not YAML, not reported'] += 1
            continue
        rows = netplan_rows(document)
        relative = context.get_relative_path(path)
        data_list.extend(row + (relative,) for row in rows)
        if rows:
            read.append(path)
    _log('Netplan Network Definitions', counts)
    return data_headers, data_list, '\n'.join(read)


def _state_folder(relative):
    return relative.replace('\\', '/').rsplit('/', 1)[0]


@artifact_processor
def networkManagerTimestamps(context):
    data_headers = (('Last Activated (UTC)', 'datetime'), 'UUID', 'Profile Name', 'Seen BSSIDs', 'Source File')
    counts = Counter()
    names = {}
    for path in _files(context, '/NetworkManager/system-connections/'):
        try:
            connection = key_file(_read(path))[0].get('connection', {})
        except OSError:
            continue
        if connection.get('uuid'):
            names.setdefault(connection['uuid'], connection.get('id', ''))
    for path in _files(context, '/etc/netplan/'):
        try:
            rows = netplan_rows(load_netplan(_read(path)))
        except (OSError, yaml.YAMLError):
            continue
        for row in rows:
            if row[4]:
                names.setdefault(row[4], row[3])
    folders = {}
    for path in _files(context, '/var/lib/NetworkManager/timestamps', '/var/lib/NetworkManager/seen-bssids'):
        relative = context.get_relative_path(path)
        try:
            groups, _ = key_file(_read(path))
        except OSError:
            counts['files that could not be read'] += 1
            continue
        store = os.path.basename(relative.replace('\\', '/'))
        entry = folders.setdefault(_state_folder(relative), {'paths': {}, 'timestamps': {}, 'seen-bssids': {}})
        entry['paths'][store] = (relative, path)
        entry[store] = groups.get(store, {})
    data_list, read = [], []
    for _, entry in sorted(folders.items()):
        for uuid in sorted(set(entry['timestamps']) | set(entry['seen-bssids'])):
            stamp = entry['timestamps'].get(uuid, '')
            when = utc(stamp)
            if stamp and when == '' and stamp.strip() != '0':
                counts['times that are not a count of seconds, Last Activated (UTC) left blank'] += 1
            data_list.append((when, uuid, names.get(uuid, ''),
                              ' | '.join(part for part in entry['seen-bssids'].get(uuid, '').split(';') if part),
                              ' | '.join(entry['paths'][store][0] for store in ('timestamps', 'seen-bssids')
                                         if uuid in entry[store])))
        read.extend(entry['paths'][store][1] for store in ('timestamps', 'seen-bssids') if entry[store])
    _log('NetworkManager Last Activation Times', counts)
    return data_headers, data_list, '\n'.join(read)
